site_name: MarkReview
docs_dir: docs
nav:
  - Home: index.md
  - Theming: theming.md
  - Accessibility: accessibility.md
  - Troubleshooting: troubleshooting.md
  - API:
      - Overview: api/index.md
