site_name: MarkReview
docs_dir: docs
nav:
  - Home: index.md
  - Usage: usage.md
  - Theming: theming.md
  - Accessibility: accessibility.md
  - Troubleshooting: troubleshooting.md
  - API:
      - Overview: api/index.md
      - CLI: api/cli.md
      - MkDocs Plugin: api/mkdocs.md
      - Docusaurus Plugin: api/docusaurus.md
