[project]
name = "mkdocs-markreview"
version = "0.1.0"
description = "MkDocs plugin for MarkReview"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [{name = "The MarkReview Team", email = "markreview@example.com"}]
classifiers = [
    "Development Status :: 4 - Beta",
    "Framework :: MkDocs",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
]
dependencies = [
    "mkdocs>=1.5",
    "pymdown-extensions>=10",
]

[project.entry-points."mkdocs.plugins"]
markreview = "markreview.plugin:MarkReviewPlugin"

[tool.setuptools.package-data]
markreview = ["assets/*"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
