[project]
name = "mkdocs-marktrace"
version = "0.1.0"
description = "MkDocs plugin for MarkTrace"
readme = "README.md"
requires-python = ">=3.8"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
