name: Codex Router
on:
  push:
    branches: ["**"]
  pull_request:
jobs:
  codex-router:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Detect next agent
        run: ./scripts/next-agent.sh
      - name: Trigger agent via Codex API
        if: env.NEXT_AGENT != ''
        run: codex run --agent "$NEXT_AGENT"
