name: Dev CI
on:
  pull_request:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install --frozen-lockfile
      - name: Set coverage threshold
        run: |
          if [ "$GITHUB_REF" = "refs/heads/main" ]; then echo "COV=90" >> $GITHUB_ENV; else echo "COV=70" >> $GITHUB_ENV; fi
      - run: pnpm exec eslint src
      - run: pnpm exec prettier --check src
      - run: pnpm exec tsc -p tsconfig.json --noEmit
      - run: pnpm audit --production
      - run: pnpm exec vitest run --coverage --coverage.failUnder=$COV
      - run: pnpm run build
      - run: pnpm run perf
