name: Dev CI
on:
  pull_request:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --with dev
          pnpm install --frozen-lockfile
      - name: Run Python checks
        run: |
          poetry run ruff check src tests
          poetry run black --check src tests
          poetry run mypy --strict src
          poetry run bandit -r src -lll --skip B101
          poetry run pip-audit -r <(pip freeze)
          poetry run pytest -q --cov=src --cov-fail-under=70
      - name: Run Node checks
        run: |
          pnpm exec eslint .
          pnpm exec prettier --check .
          pnpm exec jest --coverage --passWithNoTests
          if [ -f playwright.config.js ] || [ -f playwright.config.ts ]; then pnpm exec playwright test; fi
      - name: Security audit (npm)
        run: pnpm audit --audit-level=high
      - name: Ensure no network calls
        run: |
          if grep -R "\b\(fetch\|axios\)\b" src packages | grep -v node_modules; then
            echo "Network calls detected" && exit 1
          fi
